MVCPosApp/Controllers/LeaveApprovalController.cs
using BusinessLogic;
using BusinessLogic.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCPosApp.Controllers
{
    public class LeaveApprovalController : Controller
    {
        // GET: ManualAttendence

        GCTL_ERP_DB_MVC_06_27Entities db = new GCTL_ERP_DB_MVC_06_27Entities();
        Crud_HRM_LeaveApprovalEntry crud = new Crud_HRM_LeaveApprovalEntry();
        ClsCommon common = new ClsCommon();
        string strMaxNO = "";
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult View_LeaveApproval(string id)
        {
            var HRApprovalStatus = new List<Model_SelectType>();
            HRApprovalStatus.Add(new Model_SelectType() { Value = "Approved", Text = "Approved" });
            HRApprovalStatus.Add(new Model_SelectType() { Value = "Canceled", Text = "Canceled" });

            ViewBag.LoadHRApprovalStatus = new SelectList(HRApprovalStatus, "Value", "Text");

            var LeaveFormatType = new List<Model_SelectType>();
            LeaveFormatType.Add(new Model_SelectType() { Value = "FullLeave", Text = "Full Leave" });

            ViewBag.LoadLeaveFormat = new SelectList(LeaveFormatType, "Value", "Text");


            ViewBag.LoadEmployee = new SelectList(db.HRM_Employee.ToList().Select(u
                          => new { FirstName = String.Format("{0}{1}{2}", u.FirstName, "-", u.EmployeeID), EmployeeID = u.EmployeeID }),
                  "EmployeeID", "FirstName");

            ViewBag.LoadDepartment = new SelectList(db.HRM_Def_Department.ToList().Select(u
                          => new { DepartmentName = u.DepartmentName, DepartmentCode = u.DepartmentCode }),
                  "DepartmentCode", "DepartmentName");

            ViewBag.LoadCompany = new SelectList(db.Core_Company.ToList().Select(u
                          => new { CompanyCode = u.CompanyCode, CompanyName = u.CompanyName }),
                  "CompanyCode", "CompanyName");

            ViewBag.LoadIS = new SelectList(db.HRM_Employee.ToList().Select(u
                           => new { FirstName = String.Format("{0}{1}{2}", u.FirstName, "-", u.EmployeeID), EmployeeID = u.EmployeeID }),
                  "EmployeeID", "FirstName");

            ViewBag.LoadHOD = new SelectList(db.HRM_Employee.ToList().Select(u
                           => new { FirstName = String.Format("{0}{1}{2}", u.FirstName, "-", u.EmployeeID), EmployeeID = u.EmployeeID }),
                  "EmployeeID", "FirstName");
            ViewBag.LoadLeaveType = new SelectList(db.HRM_ATD_LeaveType, "LeaveTypeId", "Name");


            if (id == null)
            {
                return View();
            }
            else
            {
                var result = crud.GetInfo(id);
                return View(result);
            }
        }
        [HttpPost]
        public ActionResult View_LeaveApproval(Model_HRM_LeaveApplicationEntry Model)
        {
            var Item = db.HRM_LeaveApplicationEntry.FirstOrDefault(x => x.LeaveAppEntryId == Model.LeaveAppEntryId);
            if (Item != null)
            {
                crud.UpdateInfo(Model.LeaveAppEntryId, Model);
                return Json(new { success = true, message = "Approve Successfully" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = "Something wrong!" }, JsonRequestBehavior.AllowGet);

            }
        }
       
        public ActionResult ApproveByMail(string id)
        {
            var Item = db.HRM_LeaveApplicationEntry.FirstOrDefault(x => x.LeaveAppEntryId == id);
            if (Item != null)
            {
                if(Item.HRApprovalStatus == "Pending")
                {
                    Model_HRM_LeaveApplicationEntry mm = new Model_HRM_LeaveApplicationEntry();
                    mm.LeaveAppEntryId = id;
                    mm.HRApprovalStatus = "Approved";
                    mm.HRApprovalRemarks = "Your Leave Approved.";
                    crud.UpdateInfo(id, mm);
                    return PartialView("_AlertView");
                }
                else
                {
                    return PartialView("_AlertView2");
                }
                
            }
            else
            {
                return PartialView("_AlertView2");

            }
        }
        
        public ActionResult RejectByMail(string id)
        {
            var Item = db.HRM_LeaveApplicationEntry.FirstOrDefault(x => x.LeaveAppEntryId == id);
            if (Item != null)
            {
                if (Item.HRApprovalStatus == "Pending")
                {
                    Model_HRM_LeaveApplicationEntry mm = new Model_HRM_LeaveApplicationEntry();
                    mm.LeaveAppEntryId = id;
                    mm.HRApprovalStatus = "Cancelled";
                    mm.HRApprovalRemarks = "Your Leave Rejected.";
                    crud.UpdateInfo(id, mm);
                    return PartialView("_AlertView");
                }
                else
                {
                    return PartialView("_AlertView2");
                }
                
            }
            else
            {
                return PartialView("_AlertView");

            }
        }
        
        public JsonResult getSingleData(string LeaveAppEntryId)
        {
            var result = crud.GetInfo(LeaveAppEntryId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getSingleDataApproved(string LeaveAppEntryId)
        {
            var result = crud.GetApprovedInfo(LeaveAppEntryId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetEmployeeInfo(string EmployeeID)
        {
            var result = crud.GetEmployeeInfo(EmployeeID);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult showInfo()
        {
            var resutl = crud.GetAllInfo();
            return Json(new { data = resutl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowApproveInfo(string CompanyCode, string DepartmentCode, string EmployeeID)
        {
            var resutl = crud.GetAllApproveInfo(CompanyCode, DepartmentCode, EmployeeID);
            return Json(new { data = resutl }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ViewPartialPopup(string LeaveAppEntryId)
        {
           
            Model_HRM_LeaveApplicationEntry result = crud.GetPopupLoadInfo(LeaveAppEntryId);
            HRM_LeaveApplicationEntry leaveInfo = (HRM_LeaveApplicationEntry)db.HRM_LeaveApplicationEntry.Where(x=> x.LeaveAppEntryId == LeaveAppEntryId).FirstOrDefault();
            if (leaveInfo == null)
            {
                return HttpNotFound();
            }            
            return PartialView("_ViewPartialPopup", result);
        }
        [HttpGet]
        public ActionResult ViewPartialPopup2(string LeaveAppEntryId, string status)
        {
            Model_HRM_LeaveApplicationEntry result = crud.GetPopupLoadInfo(LeaveAppEntryId);
            result.HRApprovalStatus = status;
            
            HRM_LeaveApplicationEntry leaveInfo = (HRM_LeaveApplicationEntry)db.HRM_LeaveApplicationEntry.Where(x => x.LeaveAppEntryId == LeaveAppEntryId).FirstOrDefault();
            if (leaveInfo == null)
            {
                return HttpNotFound();
            }
            if (leaveInfo.HRApprovalStatus != "Pending")
            {
                return Json(new { success = false, message = "Action submitted you cant change it now!" }, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_ViewPartialPopup2", result);
        }

    }
}

MVCPosApp/Views/LeaveApproval/_ViewPartialPopup.cshtml
@model BusinessLogic.Repository.Model_HRM_LeaveApplicationEntry
 
   <div >
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Application Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @*<div class="modal-body">
                <table class="tablemodel">

                    <tr>
                    <tr>
                        Notes:
                    </tr>
                    <tr>
                        @Html.DisplayFor(Model => Model.EmployeeID)
                    </tr>

                </table>
            </div>*@
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-6">
                    <label for="inputName">Employee</label>
                    @Html.TextBoxFor(model => model.EmployeeID, new { @readonly = "readonly", @class = "form-control" })
                </div>
                <div class="col-lg-6">
                    <label for="inputName">Name</label>
                    @Html.TextBoxFor(model => model.EmployeeName, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <label for="inputName">Department</label>
                    @Html.TextBoxFor(model => model.DepartmentCode, new { @readonly = "readonly", @class = "form-control" })
                </div>
                <div class="col-lg-6">
                    <label for="inputName">Designation</label>
                    @Html.TextBoxFor(model => model.DesignationCode, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <label for="inputName">Immediate Supervisor</label>
                    @Html.TextBoxFor(model => model.BossEmpAutoId, new { @readonly = "readonly", @class = "form-control" })
                </div>
                <div class="col-lg-6">
                    <label for="inputName">Head of Department</label>
                    @Html.TextBoxFor(model => model.HOD, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <label for="inputName">Apply Leave Format</label>
                    @Html.TextBoxFor(model => model.ApplyLeaveFormat, new { @readonly = "readonly", @class = "form-control" })
                </div>
                <div class="col-lg-6">
                    <label for="inputName">Leave Type</label>
                    @Html.TextBoxFor(model => model.LeaveTypeId, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <label for="inputName">From</label>
                    <div class="input-group date">
                        @Html.TextBoxFor(model => model.StartDate, new { @readonly = "readonly", @class = "form-control", @Id = "txtStartDate" })
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="far fa-calendar"></i></div>
                        </div>
                    </div>

                </div>
                <div class="col-lg-4 ">
                    <label for="inputName">Day(s)</label>
                    @Html.TextBoxFor(model => model.NoOfDay, new { @readonly = "readonly", @class = "form-control" })
                </div>
                <div class="col-lg-4">
                    <label for="inputName">To</label>
                    <div class="input-group date">
                        @Html.TextBoxFor(model => model.EndDate, new { @readonly = "readonly", @class = "form-control", @Id = "txtStartDate" })
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="far fa-calendar"></i></div>
                        </div>
                    </div>

                </div>
            </div>

            @if (Model.ApplyLeaveFormat == "ShortLeave")
            {
                <div id="divleaveformat" class="row" style="">
                    <div class="col-lg-4">
                        <label for="inputName">From Time</label>
                        <div class="input-group date">
                            @Html.TextBoxFor(model => model.ShortLeaveFrom, new {  @class = "form-control timepicker", @Id = "fromTime" })
                            <div class="input-group-append">
                                <div class="input-group-text"><i class="far fa-clock"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <label for="inputName">Time(s)</label>
                        <div class="input-group date">
                            @Html.TextBoxFor(model => model.ShortLeaveTime, new { @readonly = "readonly", @class = "form-control ", @Id = "totalTime" })
                            <div class="input-group-append">
                                <div class="input-group-text"><i class="far fa-clock"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <label for="inputName">To</label>
                        <div class="input-group date">
                            @Html.TextBoxFor(model => model.ShortLeaveTo, new { @class = "form-control timepicker", @Id = "toTime" })
                            <div class="input-group-append">
                                <div class="input-group-text"><i class="far fa-clock"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="row">
                <div class="col-lg-12">
                    <label for="inputName">Reason</label>
                    @Html.TextAreaFor(model => model.Reason, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>


        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                @*<button type="button" id="btnsubmit" class="btn btn-primary">Save changes</button>*@
            </div>
        </div>
    </div>
<script>

    $(document).ready(function () {


        $("#btnsubmit").click(function () {
            alert();
            $("#loaderDiv").show();

            var myformdata = $("#myForm").serialize();

            $.ajax({

                type: "POST",
                url: "/Test/Index",
                data: myformdata,
                success: function () {
                    $("#loaderDiv").hide();
                    $("#myModal").modal("hide");

                }

            })
        });        
    })


</script>

MVCPosApp/Views/LeaveApproval/_ViewPartialPopup2.cshtml
@model BusinessLogic.Repository.Model_HRM_LeaveApplicationEntry

<div>
    <div class="modal-content">
        <div class="modal-header" style="background-color: #bd4949;color: white;">
            <h5 class="modal-title" id="exampleModalLabel">Any Confirmation Remarks?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="form">
                <fieldset id="SubmitForm">
                    @Html.HiddenFor(model => model.LeaveAppEntryId, new { @id = "txtLeaveAppEntryId" })
                    @Html.HiddenFor(model => model.HRApprovalStatus, new { @id = "txtHRApprovalStatus" })
                    <div class="form-group">
                        @Html.TextAreaFor(model => model.HRApprovalRemarks, new { @id = "txtHRApprovalRemarks", @style = "height: 120px;", @class = "form-control", @placeholder = "Approval Remarks" })
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" id="btnsubmit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#btnsubmit").click(function () {
            var datas = $("#SubmitForm").serialize();
            $.ajax({
                async: true,
                type: "POST",
                url: '@Url.Action("View_LeaveApproval", "LeaveApproval")',
                data: datas,
                success: function () {
                    $("#myModal").modal("hide");
                    window.location.href = "/LeaveApproval/View_LeaveApproval";
                     
                }
            })
        });
    })


</script>